name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev
          cargo install cargo-binstall
          cargo binstall --strategies crate-meta-data jj-cli

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: |
          cargo fmt --all -- --check

      - name: Run clippy
        run: |
          cargo clippy --all-features --all-targets -- -D warnings

      - name: Run tests
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          cargo test
