on: push
name: Clippy check
env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          cargo clippy --all-features --all-targets
